using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class NameList 
{
    public static List<string> maleNamesList = new List<string>() { 
        "Akito",
        "Arthur",
        "Bernard",
        "Celso",
        "Clebinho",
        "Cloud",
        "Daemon",
        "Dustin",
        "Falco",
        "Gabriel",
        "Guilherme",
        "Henrique",
        "Henry",
        "James",
        "Johnny",
        "Jun",
        "Kael",
        "Kim",
        "King",
        "Lancelot",
        "Matheus",
        "Meu",
        "Mike",
        "Petrus",
        "Rodrigo",
        "Robert",
        "Roque",
        "Thales",
        "Vitor",
        "Walter",
        "Xandão",
        "Zé",
        "Zidane",
    };

    public static List<string> femaleNamesList = new List<string>() {
        "Alice",
        "Amelie",
        "Bruna",
        "Cercei",
        "Charlotte",
        "Debby",
        "Emma",
        "Eun-na",
        "Fay",
        "Glory",
        "Iara",
        "Karen",
        "Kimiko",
        "Luna",
        "Mary",
        "Mia",
        "Milena",
        "Mima",
        "Nancy",
        "Olivia",
        "Orc",
        "Pam",
        "Peter",
        "Queen",
        "Renata",
        "Sakura",
        "Sarah",
        "Sophie",
        "Videl",
        "Yume",
        "Zaya",
    };

    public static List<string> surnameList = new List<string>() 
    {
        "Alves",
        "Antunes",
        "Bacelar",
        "Blood",
        "Brown",
        "Campbell",
        "Darkblood",
        "De Aldebaran",
        "Depp",
        "Ehrmantraut",
        "El Cid",
        "Froes",
        "Gostosa",
        "Green",
        "Guigo",
        "Hideki",
        "Jane",
        "Lannister",
        "Lee",
        "Liddell",
        "Lima",
        "Loyde",
        "Moore",
        "Morgan",
        "Oliveira",
        "Pattinson",
        "Parker",
        "Pires",
        "Pyo",
        "Rodrigues",
        "Silva",
        "Smith",
        "Stark",
        "Tsunoda",
        "Ungrateful",
        "Walker",
        "White",
        "Xavier",
    };
}
